version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: grader-postgres
    environment:
      POSTGRES_USER: grader
      POSTGRES_PASSWORD: grader
      POSTGRES_DB: grader
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grader -d grader"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pgdata: {}
